FROM ubuntu:16.04

RUN apt-get update && apt-get install -y curl vim nfs-common iproute dnsutils iputils-ping telnet zip

COPY /drone/src/bin /drone/src/launch-manager /usr/local/sbin/
COPY /drone/src/driver /

VOLUME /usr/local/sbin
EXPOSE 9500
CMD ["launch-manager"]
